// Fully populated shapes.js with tasteful gradient colors for each shape config

const shapeConfigs = [
  {
    name: "spongebabies",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 580,
    expandedScale: 1,
    image: "images/sb/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Project lead/design and sound | Name; Rob Leahy, Role; Master coder",
    tools: "Photoshop, Illustrator, Cinema 4D, Unity 3D, Audacity, After Effects, Garage band",
    title: "Spongebabies",
    subtitle: "Super fun puzzle game for all ages",
    meta: "iOS, Android, tablet/phone App",
    body: "Welcome to a world where being magnetic, hovering, rolling, swinging and teleportation are commonplace. A world where babies grow into eggs that hatch into bigger babies that grow even larger with water. This world is the home-world of the Sponge Babies. They are looking for the most talented crew to ready their ship for a mission to the next world to populate. You help them on their way to glory.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'image', src: 'images/sb/characters.jpg' },
    { type: 'image', src: 'images/sb/home.jpg' },
    { type: 'image', src: 'images/sb/c1.jpg' },
    { type: 'image', src: 'images/sb/c2.jpg' },
    { type: 'image', src: 'images/sb/c3.jpg' },
    { type: 'image', src: 'images/sb/c4.jpg' },
    { type: 'image', src: 'images/sb/WhatdoNEW.jpg' },
    { type: 'image', src: 'images/sb/Toybox.jpg' },
    { type: 'text', content: '' },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "monsterpinball",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 230,
    expandedScale: 1,
    videoSrc: "images/Pinball/MPHDqloop2.mp4",
    title: "Monster Pinball HD",
    subtitle: "Six interconnected tables of madness",
    meta: "iOS, Android Game · Launched 2010",
    body: "A concept merging physical pinball machines with digital chaos. This game earned Apples App of the week with the first iteration on the iPhone 1 and gained wide success leading to a number of progressive updates. Now decommissioned it earnt a place in Pinball history and I'm thinking of reviving it for the nostalgia.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'videoSrc', src: 'images/Pinball/MPHD.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    { type: 'image', src: 'images/Pinball/MPHDscreenshots.jpg' }
    ]
  },
  {
    name: "multiballpinball",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 230,
    expandedScale: 1.5,
    image: "images/Pinball/MultiballT1.jpg",
    title: "Multiball Pinball",
    subtitle: "Three balls, three times the madness",
    meta: "iOS, Android Game · Launched 2011",
    body: "We figured if we could get three balls going at 60fps then we should and we should make it metally challenging in all sorts of ways."
  },
  {
    name: "flappy",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 200,
    expandedScale: 1.5,
    image: "images/Flappy/thumbnails.png",
    title: "Flappy Death Run",
    subtitle: "Three balls, three times the madness",
    meta: "iOS, Android Game · Launched 2014",
    body: "We figured if we could get three balls going at 60fps then we should and we should make it metally challenging in all sorts of ways."
  },
  {
    name: "comic",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 350,
    expandedScale: 1.5,
    image: "images/Comic/cover.jpg",
    title: "Zach & Dooey",
    subtitle: "A Smart Grid Simulation",
    meta: "Web · Prototype",
    body: "Explore energy flows and grid interactions in a highly visual, interactive village simulation."
  },
  {
    name: "batterytool",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 313,
    expandedScale: 1.5,
    image: "images/BatteryTool/cover.jpg",
    title: "Home Solar Battery Usage",
    subtitle: "Enabling users to understand and calculate their home battery usage.",
    meta: "Part of a larger iOS app",
    body: "Craft, build, and thrive on your own procedurally generated island in this relaxing sandbox game."
  },
  {
    name: "ao",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 150,
    expandedScale: 1.5,
    image: "images/ao/isotruck.gif",
    title: "Isometricao",
    subtitle: "Interactive Geometry Playground",
    meta: "Web App · Interactive",
    body: "Play with isometric shapes and principles in this dynamic educational visualization tool."
  },
  {
    name: "timeline",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 400,
    expandedScale: 1.5,
    image: "images/TimelineStory/cover.jpg",
    title: "Solar Sales Timeline",
    subtitle: "Location-Based Utility",
    meta: "Mobile · Utility",
    body: "Track your movements or assets in real-time with an intuitive, privacy-focused app."
  },
  {
    name: "proposal",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 313,
    expandedScale: 1.5,
    image: "images/Proposal/cover.jpg",
    title: "Solar Sales Proposal",
    subtitle: "Location-Based Utility",
    meta: "Mobile · Utility",
    body: "Track your movements or assets in real-time with an intuitive, privacy-focused app."
  },
  {
    name: "hubana",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 400,
    expandedScale: 1.5,
    videoSrc: "images/hubana/HomeRunIntroS.mov",
    title: "Hubana HomeRun",
    subtitle: "Door Knocking App for solar sales",
    meta: "iOs, Android. Release pending.",
    body: "Keeping track of your alocated area, your goals, your customer and loging responses is easy with the right tools. We've bundled a whole lot more into this one to make life easier for everyone. Be on the lookout.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'videoSrc', src: 'images/hubana/HomeRunE.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "knock",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 300,
    expandedScale: 1.5,
    videoSrc: "images/sunobi/KnockIntroTrim3u.mp4",
    title: "Solar App",
    subtitle: "Energy Monitoring Tool",
    meta: "Web + Mobile · Utility",
    body: "Analyze solar energy consumption and battery use across installations in real-time."
  },
  {
    name: "sunobi",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 250,
    expandedScale: 1.5,
    videoSrc: "images/sunobi/SiteAnimation2u.mp4",
    title: "Branding Sunobi",
    subtitle: "Visual Identity Exploration",
    meta: "Design · Branding",
    body: "A dynamic showcase of logo explorations, typography trials, and branding palettes."
  },
  {
    name: "tommytooth",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 370,
    expandedScale: 1.5,
    image: "images/TommyTooth/cover.jpg",
    title: "Tommy Tooth",
    subtitle: "A day in the life of Tommy Tooth",
    meta: "Childrens book, published by Bonnie Books NZ.",
    body: "Childrens educational short story to encourage teeth brushing."
  },
  {
    name: "paintings",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 370,
    expandedScale: 1.5,
    image: "images/paintings/WavePainting.jpg",
    title: "Paintings",
    subtitle: "A small collection of paint on canvas",
    meta: "Showcase · Assets",
    body: "It's not all about digital of course, so when I have a space on a wall that needs filling then getting out the paints can work for that.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'image', src: 'images/paintings/WavePainting.jpg' },
    { type: 'text', content: 'This is a wave I like to surf at my local beach break. Acrylic on canvas. 600x1000mm.' },
    { type: 'image', src: 'images/paintings/forBonnie.jpg', cornerRadius: 2000 },
    { type: 'text', content: 'Painted for my daughter in her first week of life. Maybe me thinking I wont be surfing for a wee while haha. Acrylic on canvas. 700mm D.' },
    { type: 'image', src: 'images/paintings/Wave2.jpg', cornerRadius: 4 },
    { type: 'text', content: 'Requested by my mother who lives on the other side of the planet. Acrylic on canvas. 500x700mm.' },
    { type: 'image', src: 'images/paintings/theBoat.jpg', cornerRadius: 30 },
    { type: 'text', content: 'A friend and I on a cherrished boat we have on our route to a favourite surf spot off shore. Acrylic on wood - epoxy resin coating. 500x200mm.' },

  ] 
  }
];
