// Fully populated shapes.js with tasteful gradient colors for each shape config

const shapeConfigs = [
  {
    name: "spongebabies",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 380,
    expandedScale: 1,
    image: "images/sb/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Project lead/design and sound | Name; Rob Leahy, Role; Master coder",
    tools: "Photoshop, Illustrator, Cinema 4D, Unity, Audacity, After Effects, Garage band",
    title: "Sponge Babies",
    subtitle: "Super fun puzzle game for all ages",
    meta: "iOS, Android, tablet/phone App",
    body: "Welcome to a world where being magnetic, hovering, rolling, swinging and teleportation are commonplace. A world where babies grow into eggs that hatch into bigger babies that grow even larger with water. This world is the home-world of the Sponge Babies. They are looking for the most talented crew to ready their ship for a mission to the next world to populate. You help them on their way to glory.",
    blocks: [
    { type: 'image', src: 'images/sb/characters.jpg' },
    { type: 'image', src: 'images/sb/Home.jpg' },
    { type: 'image', src: 'images/sb/c1.jpg' },
    { type: 'image', src: 'images/sb/c2.jpg' },
    { type: 'image', src: 'images/sb/c3.jpg' },
    { type: 'image', src: 'images/sb/c4.jpg' },
    { type: 'image', src: 'images/sb/WhatdoNEW.jpg' },
    { type: 'image', src: 'images/sb/Toybox.jpg' },
    { type: 'text', content: '' },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "Satellite",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 300,
    expandedScale: 1,
    videoSrc: "images/Satellite/covercol.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, Cinema 4D, Unity",
    title: "Operations viewer",
    subtitle: "Behind the scenes visualiser",
    meta: "iOS, Android, Tablet App",
    body: "Going down the path of gamifying the operations of the solar business with this visualiser. A way for any member to see exactly what stage the selected job is at.",
    blocks: [
    { type: 'videoSrc', src: 'images/Satellite/runthrough.mp4' },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "monsterpinball",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 200,
    expandedScale: 1,
    videoSrc: "images/Pinball/MPHDqloop2.mp4",
    team:  "Name; Hamish Cooper, Role; Project lead/design and sound | Name; Laurance Barber, Role; Master coder",
    tools: "Photoshop, Illustrator, Cinema 4D, Unity, Audacity, After Effects, Various audio software",
    title: "Monster Pinball HD",
    subtitle: "Six interconnected tables of madness",
    meta: "iOS, Android Game · Launched 2010",
    body: "A concept merging physical pinball machines with digital chaos. This game earned Apples App of the week with the first iteration on the iPhone 1 and gained wide success leading to a number of progressive updates. Now decommissioned it earnt a place in Pinball history and I'm thinking of reviving it for the nostalgia.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'videoSrc', src: 'images/Pinball/MPHD.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    { type: 'image', src: 'images/Pinball/MPHDscreenshots.jpg' }
    ]
  },
  {
    name: "multiballpinball",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 250,
    expandedScale: 1.5,
    videoSrc: "images/Pinball/MultiballvidQ.mp4",
    team:  "Name; Hamish Cooper, Role; Project lead/design and sound | Name; Laurance Barber, Role; Master coder",
    tools: "Photoshop, Illustrator, Cinema 4D, Unity, After Effects, Various audio software",
    title: "Multiball Pinball",
    subtitle: "Three balls, three times the madness",
    meta: "iOS, Android Game · Launched 2011",
    body: "We figured if we could get three balls going at 60fps then we should and we should make it metally challenging in all sorts of ways.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'image', src: 'images/Pinball/MultiballT1.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/Pinball/MultiballT2.jpg' },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "flappyfish",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 50,
    expandedScale: 1.5,
    image: "images/Flappy/fishflywideL.gif",
    noShadow: true,        // disables outer box-shadow on this card
    noInnerShadow: true,   // disables the inner shadow overlay on its media
    team:  "Name; Hamish Cooper, Role; Project lead/design and sound | Name; Thomas Wood, Role; Master coder",
    tools: "Photoshop, Illustrator, Unity, After Effects, Various audio software",
    title: "Flappy Death Run",
    subtitle: "A take on the simplistic but hugely successful Flappy Bird.",
    meta: "iOS, Android Game · Launched 2014",
    body: "Yes I thought we could jump on the band wagon with this idea but of course take it much further. A fun little game and a project that was pretty much done in about 2 months.",
    blocks: [
    { type: 'image', span: 12, src: 'images/Flappy/header.jpg', cornerRadius: 10 },
    { type: 'image', span: 2, src: 'images/Flappy/fishfly.gif' },
    { type: 'image', span: 2, src: 'images/Flappy/manfly.gif' },
    { type: 'image', span: 2, src: 'images/Flappy/birdfly.gif' },
    { type: 'image', span: 12, src: 'images/Flappy/FDR-chopped.png', cornerRadius: 30 },
    { type: 'image', span: 12, src: 'images/Flappy/FDR-catleap.png', cornerRadius: 30 },
    { type: 'image', span: 12, src: 'images/Flappy/FDR-birdzilla.png', cornerRadius: 30 },
    { type: 'videoSrc', span: 12, src: 'images/Flappy/FlappyDeathRun.mp4' },
    { type: 'image', span: 2, src: 'images/Flappy/bbb.gif' },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "flappy",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 200,
    expandedScale: 1.5,
    image: "images/Flappy/thumbnails.png",
    team:  "Name; Hamish Cooper, Role; Project lead/design and sound | Name; Thomas Wood, Role; Master coder",
    tools: "Photoshop, Illustrator, Unity, After Effects, Various audio software",
    title: "Flappy Death Run",
    subtitle: "A take on the simplistic but hugely successful Flappy Bird.",
    meta: "iOS, Android Game · Launched 2014",
    body: "Yes I thought we could jump on the band wagon with this idea but of course take it much further. A fun little game and a project that was pretty much done in about 2 months.",
    blocks: [
    { type: 'image', span: 12, src: 'images/Flappy/header.jpg', cornerRadius: 30 },
    { type: 'image', span: 2, src: 'images/Flappy/fishfly.gif' },
    { type: 'image', span: 2, src: 'images/Flappy/manfly.gif' },
    { type: 'image', span: 2, src: 'images/Flappy/birdfly.gif' },
    { type: 'image', span: 12, src: 'images/Flappy/FDR-chopped.png', cornerRadius: 30 },
    { type: 'image', span: 12, src: 'images/Flappy/FDR-catleap.png', cornerRadius: 30 },
    { type: 'image', span: 12, src: 'images/Flappy/FDR-birdzilla.png', cornerRadius: 30 },
    { type: 'videoSrc', span: 12, src: 'images/Flappy/FlappyDeathRun.mp4' },
    { type: 'image', span: 2, src: 'images/Flappy/bbb.gif' },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "comic",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 328,
    expandedScale: 1.5,
    /*image: "images/Comic/cover.jpg",*/
    videoSrc: "images/Comic/headturn.mp4",
    team:  "Name; Hamish Cooper, Role; Prompt Designer / Image Refining / Story / Layout | Name; AI, Role; Image interpretator",
    tools: "Photoshop, Illustrator, Unity 3D, After Effects, Various audio software",
    title: "Zach & Dooey",
    subtitle: "The Jendehya Circuit Part 1",
    meta: "Graphic Novel",
    body: "Exploring the unimagined via their crepuscular engine. What is strange is normal to these two imagineers. Everything is not what it seems in an adventure of multi-dimensional challlenges. Astory about navigating the strange both at home and beyond time itself.",
    blocks: [
    { type: 'image', src: 'images/Comic/OpenBook.jpg'},
    { type: 'image', src: 'images/Comic/gnbook.jpg'},
    { type: 'image', src: 'images/Comic/gncover.jpg'},
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "cloud",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 177,
    expandedScale: 1.5,
    videoSrc: "images/Comic/cloudlighten.webm",
    noShadow: true,        // disables outer box-shadow on this card
    noInnerShadow: true,   // disables the inner shadow overlay on its media
    team:  "Name; Hamish Cooper, Role; Prompt Designer / Image Refining / Story / Layout | Name; AI, Role; Image interpretator",
    tools: "Photoshop, Illustrator, Unity 3D, After Effects, Various audio software",
    title: "Zach & Dooey",
    subtitle: "The Jendehya Circuit Part 1",
    meta: "Graphic Novel",
    body: "Exploring the unimagined via their crepuscular engine. What is strange is normal to these two imagineers. Everything is not what it seems in an adventure of multi-dimensional challlenges. Astory about navigating the strange both at home and beyond time itself.",
    blocks: [
    { type: 'image', src: 'images/Comic/OpenBook.jpg'},
    { type: 'image', src: 'images/Comic/gnbook.jpg'},
    { type: 'image', src: 'images/Comic/gncover.jpg'},
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "batterytool",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 300,
    expandedScale: 1.5,
    image: "images/BatteryTool/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, Cinema 4D, Unity",
    title: "Home Solar Battery Usage",
    subtitle: "Enabling users to understand and calculate their home battery usage.",
    meta: "Part of a larger iOS app",
    body: "The Battery Tool in the video below is Part of the Sunobi tool set. This tool is designed to help Reps explain home battery usage to their customers. It is customer facing too which allows both parties to edit and discover of the fly what battery and how many they might need under any given situation or desire.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'videoSrc', src: 'images/BatteryTool/BatteryToolQuick.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "icp",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 150,
    expandedScale: 1.5,
    image: "images/ICP/cover2.jpg",
    team:  "Name; Hamish Cooper, Role; Design / Animation / Composition | Name; Flavour Designs, Role; New Zealand",
    tools: "After Effects, Photoshop, Cinema 4D, Various Audio Editors",
    title: "Iwi Collective Partnership",
    subtitle: "ICP exhibition and conference introduction video.",
    meta: "Commissioned to Flavour Designs NZ",
    body: "The goal was simply to make the audience feel part of something great while keeping the subject simple. An intro.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'videoSrc', src: 'images/ICP/ICP.mp4'},
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "designtool",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 470,
    expandedScale: 1.5,
    image: "images/DesignTool/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, Cinema 4D, After Effects, Unity",
    title: "Solar Panel Roof Layout Designer",
    subtitle: "Enabling users to build solar panel layouts automatically, edit layouts and calculate outcomes.",
    meta: "Part of a larger iOS app",
    body: "This tool is built for Reps to quickly build proposals for customers. It's automatic detection and edit capabilities set it apart from other tools along with it's usability and flexability. It can auto generate in seconds and feeds directly into their proposals within our expanded app.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'videoSrc', src: 'images/DesignTool/designercomp.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "ao",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    /*height: 120,*/
    height: 300,
    expandedScale: 1.5,
    /*image: "images/ao/isotruck.gif",*/
    videoSrc: "images/ao/christmasbirthday.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct",
    tools: "Photoshop, Cinema 4D, After Effects, Adobe XD",
    title: "AO UK",
    subtitle: "A wide range of work from website widget designs to advertising to App design and video.",
    meta: "Web and native device apps",
    body: "Too much to cover here. There were 5-50 tasks a day with this work so staying true to the craft was a constant toss up between what I felt needed more work to saying ok it's good enough, next. But I loved my time on these things. Great people made it fun.",
    blocks: [
    { type: 'image', src: 'images/ao/items.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/isobanner.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/isotruck.gif', cornerRadius: 30 },
    { type: 'videoSrc', src: 'images/ao/boxingday.mov', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/wrappedup.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/xmas1.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/xmas2.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/bf.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/pages.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/samsung.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/ao/app.jpg', cornerRadius: 30 },
    { type: 'videoSrc', src: 'images/ao/app.mp4', cornerRadius: 30 },
    { type: 'videoSrc', src: 'images/ao/birthday.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "timeline",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 400,
    expandedScale: 1.5,
    image: "images/TimelineStory/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, Unity",
    title: "Solar Sales Timeline",
    subtitle: "Explaining the path to Solar as quick as possible while making a sale.",
    meta: "Web, App and Print",
    body: "Reps are often faced with either not telling the customer enough or too much. It's a fine line with sales in an industry that should be a no brainer. This peice is one of many that aim to bridge that gap as succinctly.",
    blocks: [
    { type: 'image', src: 'images/TimelineStory/SolarStory.jpg', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "proposal",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 268,
    expandedScale: 1.5,
    image: "images/Proposal/cover2.jpg",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, Unity",
    title: "Solar Sales Proposal",
    subtitle: "Everything the customer needs to know regarding their chosen solar deal.",
    meta: "Web, App",
    body: "Solar proposals are all too often left as an afterthought when they are arguably the most critical aspect. We tried to give customers the ability to make an informed decision without boring them or leaving them confused and doubtful. Solar is good and deserves a good proposal.",
    blocks: [
    { type: 'image', src: 'images/Proposal/ProposalLong.jpg', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "hubana",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 400,
    expandedScale: 1.5,
    videoSrc: "images/Hubana/HomeRunIntroS.mov",
    team:  "Name; Hamish Cooper, Role; Design/Construct",
    tools: "Photoshop, Adobe XD, Unity",
    title: "Hubana rebrand",
    subtitle: "Rebrand and reskinning of the Sunobi Door Knocking App for solar sales",
    meta: "iOs, Android. Release pending.",
    body: "Keeping track of your allocated area, your goals, your customer and loging responses is easy with the right tools. We've bundled a whole lot more into this one to make life easier for everyone. Be on the lookout.",
    blocks: [
    { type: 'videoSrc', span: 4, src: 'images/Hubana/HomeRunE.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "themarket",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 440,
    expandedScale: 1.5,
    videoSrc: "images/TM/appcover.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct",
    tools: "Photoshop, Cinema 4D, After Effects, Adobe XD, Hype",
    title: "TheMarket",
    subtitle: "New Zealands premium and globally sourced online shopping platform",
    meta: "iOs, Android & Web",
    body: "My role as lead designer was to design the brand, platform UI and UX, design guidelines for robust flexability and growth and guide the greater design team. It was a great time with great people. The fact that the company went under after 5 years was not my fault haha. It was a success until management changed.",
    blocks: [
    { type: 'image', src: 'images/TM/aboutus.jpg'},
    { type: 'image', src: 'images/TM/curtains.jpg'},
    { type: 'image', src: 'images/TM/brand.jpg'},
    { type: 'image', src: 'images/TM/join.jpg'},
    { type: 'image', src: 'images/TM/premium.jpg'},
    { type: 'image', src: 'images/TM/toys.jpg'},
    { type: 'image', src: 'images/TM/t1.jpg'},
    { type: 'image', src: 'images/TM/t2.jpg'},
    { type: 'image', src: 'images/TM/t3.jpg'},
    { type: 'image', src: 'images/TM/t4.jpg'},
    { type: 'image', src: 'images/TM/t5.jpg'},
    { type: 'image', src: 'images/TM/launch2.jpg'},
    { type: 'videoSrc', src: 'images/TM/advert.mp4', cornerRadius: 30 },
    { type: 'videoSrc', src: 'images/TM/CNY2020.mp4', cornerRadius: 30 },
    { type: 'videoSrc', src: 'images/TM/8sWide.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "knock",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 350,
    expandedScale: 1.5,
    videoSrc: "images/knock/walk.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, After Effects, Unity",
    title: "Knock",
    subtitle: "Solar Door Knocking App",
    meta: "Web + Mobile · App",
    body: "Solar sales door knocking and lead generation App designed to make life 'fun, fast and easy' for Reps and Managers.",
    blocks: [
    { type: 'image', src: 'images/Knock/k5.png'},
    { type: 'image', src: 'images/Knock/k2.jpg'},
    { type: 'image', src: 'images/Knock/k1.jpg'},
    { type: 'image', src: 'images/Knock/k3.jpg'},
    { type: 'image', src: 'images/Knock/k6.jpg'},
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "orgchart",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 300,
    expandedScale: 1.5,
    videoSrc: "images/OrgChart/ocsmall.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, After Effects, Unity",
    title: "Org Chart",
    subtitle: "Organisational Chart Creation App Segment",
    meta: "Web + Mobile · App",
    body: "Part of the larger Sunobi Sales App.",
    blocks: [
    { type: 'videoSrc', src: 'images/OrgChart/oc1.mp4'},
    { type: 'image', src: 'images/Sales/02.jpg'},
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "sales",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 300,
    expandedScale: 1.5,
    videoSrc: "images/Sales/loop.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, After Effects, Unity",
    title: "Sunobi Sales",
    subtitle: "Solar Sales Application to educate and sign roof solar",
    meta: "Web + Mobile · App",
    body: "This App is a seemlessly linked collection powerfull tools to help Reps and Managers sell, manage, sign and implement roof solar deals.",
    blocks: [
    { type: 'image', src: 'images/Sales/01.jpg'},
    { type: 'image', src: 'images/Sales/03.jpg'},
    { type: 'image', src: 'images/Sales/04.jpg'},
    { type: 'image', src: 'images/Sales/05.jpg'},
    { type: 'image', src: 'images/Sales/07.jpg'},
    { type: 'image', src: 'images/Sales/08.jpg'},
    { type: 'image', src: 'images/Sales/09.jpg'},
    { type: 'image', src: 'images/Sales/10.jpg'},
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "sunobi",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 250,
    expandedScale: 1.5,
    videoSrc: "images/Sunobi/SiteAnimation2u.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, After Effects, Webflow, Lottie",
    title: "Sunobi Branding, Website, Social...",
    subtitle: "Visual Identity For A Solar Software Company",
    meta: "Design · Branding",
    body: "Just the beginning. Many projects unfolded for this company in developing and designing their suite of software. Explore my portfolio to see the other linked projects.",
    blocks: [
    { type: 'image', src: 'images/Sunobi/logo1.jpg'},
    { type: 'image', src: 'images/Sunobi/logo2.jpg'},
    { type: 'image', src: 'images/Sunobi/logo3.jpg'},
    { type: 'image', src: 'images/Sunobi/logo4.jpg'},
    { type: 'image', src: 'images/Sunobi/val1.jpg'},
    { type: 'image', src: 'images/Sunobi/val2.jpg'},
    { type: 'image', src: 'images/Sunobi/val3.jpg'},
    { type: 'image', src: 'images/Sunobi/phones.jpg'},
    { type: 'image', src: 'images/Sunobi/merch1.jpg'},
    { type: 'image', src: 'images/Sunobi/merch2.jpg'},
    { type: 'image', src: 'images/Sunobi/merch3.jpg'},
    { type: 'image', src: 'images/Sunobi/photos.jpg'},
    { type: 'image', src: 'images/Sunobi/xd.jpg'},
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "tommytooth",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 370,
    expandedScale: 1.5,
    image: "images/TommyTooth/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Design/Layouts | Name; Tia Cooper, Role; Story/Ideation/Research | Name; Copyright, Role; 2025 Tia Cooper | Name; Published by, Role; Bonnie Books NZ | Name; ISBN, Role; 978-1-0671052-2-8",
    tools: "Pro Create, Photoshop, InDesign",
    title: "Tommy Tooth",
    subtitle: "A day in the life of Tommy Tooth",
    meta: "Childrens book, published by Bonnie Books NZ.",
    body: "Childrens educational short story to encourage teeth brushing.",
    blocks: [
    { type: 'videoSrc', span: 4, src: 'images/TommyTooth/TT.mp4', cornerRadius: 30 },
    { type: 'image', span: 8, src: 'images/TommyTooth/bookdesk.jpg', cornerRadius: 30 },
    { type: 'image', span: 14, src: 'images/TommyTooth/TTpages.jpg', cornerRadius: 6 },
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "unison",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 230,
    expandedScale: 1.5,
    videoSrc: "images/Unison/loop.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Animation/Video/Sound | Name; Tracta Design Agency, Role; Napier, NZ",
    tools: "Photoshop, After Effects, Various Audio Software",
    title: "Unison",
    subtitle: "The Powerlines People",
    meta: "Promotional material.",
    body: "Wanting to reach a wide audiance with low level knowledge of the company.",
    blocks: [
    { type: 'videoSrc', src: 'images/Unison/Unison.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' }
    ]
  },
  {
    name: "paintings",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 370,
    expandedScale: 1.5,
    image: "images/paintings/WavePainting.jpg",
    team:  "Name; Hamish Cooper, Role; Painting",
    tools: "Canvas, Acrylic paints, Brushes",
    title: "Paintings",
    subtitle: "A small collection of paint on canvas",
    meta: "Showcase · Assets",
    body: "It's not all about digital of course, so when I have a space on a wall that needs filling then getting out the paints can work for that.",
    blocks: [
    { type: 'text', content: ' ' },
    { type: 'image', src: 'images/paintings/WavePainting.jpg'},
    { type: 'text', content: 'This is a wave I like to surf at my local beach break. Acrylic on canvas. 600x1000mm.' },
    { type: 'image', src: 'images/paintings/forBonnie.jpg', cornerRadius: 2000 },
    { type: 'text', content: 'Painted for my daughter in her first week of life. Maybe me thinking I wont be surfing for a wee while haha. Acrylic on canvas. 700mm D.' },
    { type: 'image', src: 'images/paintings/Wave2.jpg', cornerRadius: 4 },
    { type: 'text', content: 'Requested by my mother who lives on the other side of the planet. Acrylic on canvas. 500x700mm.' },
    { type: 'image', src: 'images/paintings/penguins.jpg', cornerRadius: 4 },
    { type: 'text', content: 'For the inlaws. 500x600mm.' },
    { type: 'image', src: 'images/paintings/theBoat.jpg', cornerRadius: 30 },
    { type: 'text', content: 'A friend and I on a cherrished boat we have on our route to a favourite surf spot off shore. Acrylic on wood - epoxy resin coating. 500x200mm.' },
    { type: 'image', src: 'images/paintings/Monster.jpg', cornerRadius: 30 },
    { type: 'text', content: 'Acrylic on canvas originally but then messed with a little in ProCreate - just a doodle really. 400x300mm.' },
    { type: 'image', src: 'images/paintings/homeworld.jpg', cornerRadius: 30 },
    { type: 'text', content: 'While working on my game SpongBabies I painted this in relation to their homeworld. 200x250mm.' },
    
  ] 
  },
  {
    name: "support",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 368,
    expandedScale: 1.5,
    image: "images/Support/cover.jpg",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, AI image generators, Unity",
    title: "Solar Sales Support",
    subtitle: "Offering a support portal to resolve and evolve.",
    meta: "Web, App",
    body: "Support is critical. This section enables support ticket creation and resolution though a simple and engaging interface. Feedback loops and management together additions give users the assurances they need with any given issue to feel 'Supported'.",
    blocks: [
    { type: 'image', src: 'images/Support/SupportTeam.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/Support/SupportLive.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/Support/SupportIdeas.jpg', cornerRadius: 30 },
    { type: 'image', src: 'images/Support/SupportComs.jpg', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
  {
    name: "eastland",
    cornerRadiusDefault: 15,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 320,
    expandedScale: 1.5,
    videoSrc: "images/Eastland/EVanimSmall.mp4",
    team:  "Name; Hamish Cooper, Role; Design/Construct | Name; Tydus Queiroz, Role; Ideation | Name; Sunobi Developers, Role; Coding",
    tools: "Adobe XD, Photoshop, AI image generators, Unity",
    title: "Solar Sales Support",
    subtitle: "Offering a support portal to resolve and evolve.",
    meta: "Web, App",
    body: "Support is critical. This section enables support ticket creation and resolution though a simple and engaging interface. Feedback loops and management together additions give users the assurances they need with any given issue to feel 'Supported'.",
    blocks: [
    { type: 'image', src: 'images/Eastland/12.webp', cornerRadius: 5 },
    { type: 'image', src: 'images/Eastland/34.webp', cornerRadius: 5 },
    { type: 'image', src: 'images/Eastland/56.webp', cornerRadius: 5 },
    { type: 'image', src: 'images/Eastland/78.webp', cornerRadius: 5 },
    { type: 'image', src: 'images/Eastland/910.webp', cornerRadius: 5 },
    { type: 'videoSrc', src: 'images/Eastland/EVanimFull.mp4', cornerRadius: 30 },
    { type: 'text', content: ' ' },
    ]
  },
];
