const shapeConfigs = [
  {
    name: "spongebabies",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 180,
    height: 240,
    expandedScale: 1.5,
    image: "images/spongebabies.jpg",
    title: "Spongebabies",
    subtitle: "Super fun puzzle game for all ages",
    meta: "iOS, Android, tablet/phone App",
    body: "Welcome to a world where being magnetic, hovering, rolling, swinging and teleportation are commonplace..."
  },
  {
    name: "pinball",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 200,
    expandedScale: 1.5,
    image: "images/ui1.gif",
    title: "Pinball",
    subtitle: "Retro Interactive Fun",
    meta: "Web Game · Launched",
    body: "A concept merging physical pinball machines with digital chaos."
  },
  {
    name: "unison",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 200,
    expandedScale: 1.5,
    image: "images/battery.gif",
    title: "Unison",
    subtitle: "Harmony-Based Sound Toy",
    meta: "Web Audio · Concept",
    body: "Create soundscapes by aligning orbs in resonant harmony."
  },
  {
    name: "electricvillage",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 210,
    height: 230,
    expandedScale: 1.5,
    image: "images/spongebabies.jpg",
    videoSrc: "images/videodemo.mp4",
    title: "Electric Village",
    subtitle: "A Smart Grid Simulation",
    meta: "Web · Prototype",
    body: "Explore energy flows and grid interactions in a highly visual, interactive village simulation."
  },
  {
    name: "island",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 220,
    expandedScale: 1.5,
    image: "images/spongebabies.jpg",
    title: "Island",
    subtitle: "Survival World Builder",
    meta: "Game · Beta Release",
    body: "Craft, build, and thrive on your own procedurally generated island in this relaxing sandbox game."
  },
  {
    name: "isometricao",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 220,
    height: 240,
    expandedScale: 1.5,
    image: "images/spongebabies.jpg",
    title: "Isometricao",
    subtitle: "Interactive Geometry Playground",
    meta: "Web App · Interactive",
    body: "Play with isometric shapes and principles in this dynamic educational visualization tool."
  },
  {
    name: "trackingapp",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 190,
    height: 200,
    expandedScale: 1.5,
    image: "images/spongebabies.jpg",
    title: "Tracking App",
    subtitle: "Personal Analytics Dashboard",
    meta: "iOS, Android · Live",
    body: "Track habits, mood, health, and performance using customizable dashboards and powerful graphs."
  },
  {
    name: "christmas",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 230,
    height: 210,
    expandedScale: 1.5,
    color: "#c0392b",
    image: "images/spongebabies.jpg",
    title: "Christmas",
    subtitle: "Festive Mini Game Collection",
    meta: "Mobile · Seasonal Event",
    body: "A joyful collection of interactive festive experiences for all ages, released each holiday season."
  },
  {
    name: "deathrun",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 240,
    height: 220,
    expandedScale: 1.5,
    color: "#2c3e50",
    image: "images/spongebabies.jpg",
    title: "Deathrun",
    subtitle: "High-Speed Obstacle Sprint",
    meta: "Game · Pre-Alpha",
    body: "Dodge, sprint, and slide your way through a deathtrap gauntlet in this high-stakes action game."
  },
  {
    name: "paintings",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 200,
    height: 260,
    expandedScale: 1.5,
    color: "#f39c12",
    image: "images/spongebabies.jpg",
    title: "Paintings",
    subtitle: "Generative Art Showcase",
    meta: "Web Gallery · Curated",
    body: "A rotating digital collection of generative art experiments and painted algorithms."
  },
  {
    name: "solarapp",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 210,
    height: 210,
    expandedScale: 1.5,
    color: "#27ae60",
    image: "images/spongebabies.jpg",
    title: "SolarApp",
    subtitle: "Residential Solar Designer",
    meta: "Tablet Tool · In Use",
    body: "Design and visualize solar panel layouts on real rooftops. Used by solar consultants in the field."
  },
  {
    name: "brandingsunobi",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 220,
    height: 200,
    expandedScale: 1.5,
    color: "#16a085",
    image: "images/spongebabies.jpg",
    title: "Branding Sunobi",
    subtitle: "Identity System Design",
    meta: "Design · Delivered",
    body: "A bold, elemental branding package for Sunobi, including motion assets and web presence."
  },
  {
    name: "brandingthemarket",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 250,
    height: 230,
    expandedScale: 1.5,
    color: "#9b59b6",
    image: "images/spongebabies.jpg",
    title: "Branding the Market",
    subtitle: "Visual Toolkit for Local Economy",
    meta: "Design · Visual System",
    body: "Identity and signage system for community-focused makers' markets and local produce hubs."
  },
  {
    name: "myinfo",
    cornerRadiusDefault: 60,
    cornerRadiusExpanded: 20,
    width: 180,
    height: 200,
    expandedScale: 1.5,
    color: "#34495e",
    image: "images/spongebabies.jpg",
    title: "My Info",
    subtitle: "Your Portfolio Credentials",
    meta: "Static · UI Element",
    body: "A self-referential block for your personal branding, showcasing name and professional summary."
  }
];